name: Build Blog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Process deploy configuration
        run: |
          sh deploy.sh
      - name: Commit build to deploy branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b deploy
          git add .
          git commit -m "Build page" -m "`date`"
          git push -f origin deploy
  call-deploy:
    needs: build
    uses: ./.github/workflows/jekyll.yml
